### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by christian-ortmann** [INFO523-S24/project-01-Stats-N-Facts#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

Christian Ortmann - @christian-ortmann

Roxana Akbarsharifi - @rxnsh

Shashank Yadav - @xinformatics

Abhishek kumar - @Abhi291712

Gorantla Sai Laasya - @Sailaasya-1

Divya Liladhar Dhole - @Divyadhole

- Describe the goal of the project.
Understanding trends in biomedical research for medications such as Covid vaccine and Hepatitis-B while still remaining authorized by government authorities.

- Describe the data used or collected.
The dataset shows comprehensive overview of pharmaceutical products. It includes details such as category, name, therapeutic area, common name, active substance, and unique product number for each medicine.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Filter the data down to the COVID-19 or Hepatitis-B variables that were approved and sort by revision number. Display the data.

- Is there anything that is unclear from the proposal?
There is no mention of what types of plots will be used to visualize the data or how they will make their conclusions. They also need to cite the source that TidyTuesday used.

- Provide constructive feedback on how the team might be able to improve their project.
Only mentioned TidyTuesday as the source, not the source from which the data was collected. No proposal title.
Provide clarity on how they intend to display the data and how they intend to make their conclusions. What statistical methods do they plan to use to analyze the data?

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
Are there any drugs that have the same active substance that are prescribed for different diseases?

- Provide constructive feedback on any issues with file and/or code organization.
The GitHub logo does not link to the Repo for this team. There is too much code in the proposal, should have suppressed the code so non-technical people can understand.

**Comment by hmfattah** [comment]
Thank you for your helpful comments. We will definitely include the original source alongside TidyTuesday. 

For this project, we won't be employing any statistical models to answer the questions. However, we do plan to explore the correlations between different variables. As the final result, we intend to display the top k results, where k might be 3, 5, or 7. We've made efforts to ensure the code is readable and understandable, with sufficient comments.
