### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by zandi-omid** [INFO523-S24/project-01-Stats-N-Facts#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members who participated in this review are 

- Omid Zandi - @zandi-omid
- Praveen Kumar Pappala - @Praveen-Kumar-Pappala
- Priom Mahmud - @Priom1996
- Deema Albluwi -@Dee-koudz
- Mohammad Farmani - @mfarmani95
- Remi Hendershott - @remisublette

- Describe the goal of the project.

The goal is to investigate the evolution of different vaccines for different diseases and learn how to manipulate large datasets. 

- Describe the data used or collected.

The dataset consists of 1988 records and 28 features, providing a comprehensive overview of various pharmaceutical products and medicines. It encompasses diverse information, including the medicine’s category, name, therapeutic area, common name, active substance, and unique product number. 

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The methods include slicing and filtering variables, arranging them in a specific order, and counting the rows.

- Is there anything that is unclear from the proposal?

They would better off showing a glimpse of the dataset, which will give an overview of how the data behaves. For example, we can not realize the categories in the categorical columns or the order of numbers in the numerical variables.

- Provide constructive feedback on how the team might be able to improve their project.

First of all, we should see the dataframe to get in touch with the nature of the dataset. Also, it seems the whole dataset is categorical dataset including the ones that have been mentioned as numerical. It is suggested to compute some summary statistics by including some ratios or percentages. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

How long does it take for a vaccine to get approved on average? How are the scientists doing with improving the vaccines for different diseases over time? 

- Provide constructive feedback on any issues with file and/or code organization.

They don't have to show the code. Also, they have to show the data frame along with the variables description. In fact, we had to look over the variables in the dataset github ourselves. 

- (Optional) Any further comments or feedback?

It seems like the dataset contains only categorical variables. Even the logical variables are also categorical, which makes the analysis difficult.

**Comment by hmfattah** [comment]
Thank you for your helpful comments. We agree that providing a glimpse of the dataset (i.e., print(dataset.head())) would have been a better idea for reviewers. We will also include some summary statistics.

Although most features are categorical, there are numerical variables as well, such as 'revision_number'. In fact, we will use that feature to answer our first question.
