### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by christian-ortmann** [INFO523-S24/project-01-Stats-N-Facts#5]
The following is the peer review of the Presentation proposal by Tech Titans. The team members that participated in this review are 

- Christian Ortmann @christian-ortmann
- Abhishek Kumar @Abhi291712
- Divya Liladhar Dhole @Divyadhole
- Roxana Akbarsharifi @rxnsh
- Gorantla Sai Laasya @Sailaasya-1
- Shashank Yadav @xinformatics

- Content: Is the research question well designed and is the data being used relevant to the research question?

Yes, it is a highly relevant question for society today and focus on medical advancements in the past few years for COVID and Hepatitis B. They used a barplot and 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, they used bar plots to quantitatively show which vaccine changed the most while still being approved. Their insights were clear as it was a reflection of the quantitative aspect of the bar plot values. For their second question they used a stacked line plot, which does a great job of showing the differences between the vaccines while also showing the growth of each. Their limitations were an excellent addition to the analysis as the data is not the easiest to visualize.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes, I liked the tab format they used, was a good way to keep the amount of slides low while still providing lots of information on the slide. Looks like they spend time making the project thoughtful and informative.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Yes the slides were very clean. There was a fair bit of text, but they did a good job of providing info that isn't written on the slides.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
Yes, everyone presented well. The online format makes the other aspects of this question difficult, but from my POV, they seemed to be well informed with their data and comfortable speaking. Didn't feel like they had a script. Everyone made good contributions and said something helpful.

**Comment by hmfattah** [comment]
Thank you for the feedback!
