### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by zandi-omid** [INFO523-S24/project-01-Stats-N-Facts#6]
The following is the peer review of the Presentation proposal by Weather Gurus. The team members that participated in this review are 

- Omid Zandi - @zandi-omid

- Praveen Kumar Pappala - @Praveen-Kumar-Pappala

- Priom Mahmud - @Priom1996

- Deema Albluwi -@Dee-koudz

- Mohammad Farmani - @mfarmani95

- Remi Hendershott - @remisublette

- Content: Is the research question well designed and is the data being used relevant to the research question?

Yes, the research questions are pretty straightforward, and the selected dataset and features are relevant.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Yes, they used suitable visualizations except the cumulative revisions which is a little bit confusing.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

The dataset contains mostly categorical variables, which limited the ability to bring out more creativity with the visualizations. They have mentioned the limitations as well. They have also put enough effort into doing the project.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

Yes, they are. The slides are readable and don't contain too much text. The plots for the second question are not easily interpretable. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

Yes, it was professional. They had practiced the presentation and finished it on time.

**Comment by hmfattah** [comment]
Thank you for the feedback!
